# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5d32e07013f67e43365fa8365fc032a75b80a8b449be30aa9fa8401f50cb2d019fb9fdd618f1260330a0e224c12d1d2a3a67d4fcd6947d9d08d009b821b0a4b

test:
  secret_key_base: 1f84062e69e2028dcc953e26223ca44db82e30b168667d268e4f8b48385201c58e01414e6eec012940c58dace819d8f801d8791d43cde6f5ae6ee0aad196a55c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
